PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS USUARIOS;

CREATE TABLE USUARIOS (
    IDUSUARIO INTEGER PRIMARY KEY,
    ACTIVO TEXT,
    CLAVE TEXT,
    CONFIRMADO TEXT,
    DOCUMENTO INTEGER UNIQUE,
    FECHA_NACIMIENTO TEXT,
    MAIL_INSTITUCIONAL TEXT,
    MAIL_PERSONAL TEXT,
    PRIMER_APELLIDO TEXT,
    PRIMER_NOMBRE TEXT,
    SEGUNDO_APELLIDO TEXT,
    SEGUNDO_NOMBRE TEXT,
    TELEFONO TEXT,
    TIPO_USUARIO TEXT,
    USUARIO TEXT UNIQUE,
    IDDEPARTAMENTO INTEGER,
    IDGENERO INTEGER,
    IDITR INTEGER,
    IDLOCALIDAD INTEGER,
    
    FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTOS(IDDEPARTAMENTO),
    FOREIGN KEY (IDGENERO) REFERENCES GENEROS(IDGENERO),
    FOREIGN KEY (IDITR) REFERENCES ITRS(IDITR),
    FOREIGN KEY (IDLOCALIDAD) REFERENCES LOCALIDADES(IDLOCALIDAD)
);
